### ISSUE TITLE
Working with 74HC166N shift register

### ISSUE THREAD

**Issue by PeterKL3** [slu4coder/Arduino-Nano-PC#1]
Hi, thanks for the terrific work.
I want to ask you how I can use your code with the other shift register you sometimes use, the 74HC166. When I use it with this code and without the XOR-Gates, it displays only every other row on the VGA monitor. Is this a timing issues? Thanks a lot. Peter

**Comment by slu4coder** [comment]
Hi Peter, the Nano PC Revision 1 relies on 74HC165. Please do not use 74HC166.

I am currently working on an update (Revision 2): 1x Nano + 1x 74HC166 = "full PC" with VGA and PS/2
Watch out for my upcoming YouTube video! Cheers!
